# Generated by Django 3.0.4 on 2023-05-22 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etapa', '0002_auto_20230522_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao_etapa', models.CharField(choices=[('DIREITA', 'Direita'), ('ESQUERDA', 'Esquerda')], max_length=8, verbose_name='Posição na quadra para esta etapa *')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atleta', to=settings.AUTH_USER_MODEL, verbose_name='Atleta *')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etapa', to='etapa.Etapa', verbose_name='Etapa da inscrição')),
            ],
            options={
                'verbose_name': 'inscrição',
                'verbose_name_plural': 'inscrições',
                'ordering': ['-etapa__data', 'atleta__nome'],
                'unique_together': {('etapa', 'atleta')},
            },
        ),
    ]
