# Generated by Django 3.0.4 on 2023-05-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscricao',
            options={'ordering': ['etapa__grupo', '-etapa__data', 'posicao_etapa', 'atleta__nome'], 'verbose_name': 'inscrição', 'verbose_name_plural': 'inscrições'},
        ),
        migrations.AddField(
            model_name='inscricao',
            name='com_dupla',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Com dupla?'),
        ),
    ]
