# Generated by Django 3.0.4 on 2023-06-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Uma pequena frase para aparecer na capa do sistema', max_length=50, verbose_name='Título da foto')),
                ('arquivo', models.FileField(help_text='Use arquivo .png para enviar seu arquivo', upload_to='midias', verbose_name='Arquivo .png')),
                ('data_publicacao', models.DateTimeField(auto_now=True, verbose_name='Data e hora de atualização do registro')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
            ],
            options={
                'verbose_name': 'foto',
                'verbose_name_plural': 'fotos',
                'ordering': ['data_publicacao', 'titulo'],
            },
        ),
    ]
