# Generated by Django 3.0.4 on 2023-06-22 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foto', '0003_auto_20230619_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foto',
            options={'ordering': ['-data_publicacao', 'titulo'], 'verbose_name': 'foto', 'verbose_name_plural': 'fotos'},
        ),
    ]
