# Generated by Django 3.0.4 on 2023-06-21 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chave', '0004_auto_20230613_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('CLASSIFICATÓRIA', 'Classificatória'), ('DEZESSEIS', 'Dezesseis'), ('DÉCIMA', 'Décima'), ('OITAVAS', 'Oitavas'), ('QUARTAS', 'Quartas'), ('SEMI', 'Semi'), ('FINAL', 'Final')], help_text='* Campos obrigatórios', max_length=15, verbose_name='Fase da etapa *')),
                ('placar_timeA_set1', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=2, null=True, verbose_name='Games vencidos Time A (1o set)')),
                ('placar_timeB_set1', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=2, null=True, verbose_name='Games vencidos Time B (1o set)')),
                ('placar_timeA_set2', models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Caso tenha ocorrido o set', max_digits=2, null=True, verbose_name='Games vencidos Time A (2o set)')),
                ('placar_timeB_set2', models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Caso tenha ocorrido o set', max_digits=2, null=True, verbose_name='Games vencidos Time B (2o set)')),
                ('placar_timeA_set3', models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Caso tenha ocorrido o set', max_digits=2, null=True, verbose_name='Games vencidos Time A (3o set)')),
                ('placar_timeB_set3', models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Caso tenha ocorrido o set', max_digits=2, null=True, verbose_name='Games vencidos Time B (3o set)')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
                ('chave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chave.Chave')),
                ('timeA_chave_dupla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timeA_chave_dupla', to='chave.ChaveDupla')),
                ('timeB_chave_dupla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timeB_chave_dupla', to='chave.ChaveDupla')),
                ('vencedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vencedor', to='chave.ChaveDupla')),
            ],
            options={
                'verbose_name': 'jogo',
                'verbose_name_plural': 'jogos',
                'ordering': ['chave'],
                'unique_together': {('fase', 'timeA_chave_dupla', 'timeB_chave_dupla')},
            },
        ),
    ]
