# Generated by Django 3.0.4 on 2023-06-21 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chave', '0004_auto_20230613_1705'),
        ('jogo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jogo',
            old_name='timeA_chave_dupla',
            new_name='timeA',
        ),
        migrations.RenameField(
            model_name='jogo',
            old_name='timeB_chave_dupla',
            new_name='timeB',
        ),
        migrations.AlterUniqueTogether(
            name='jogo',
            unique_together={('fase', 'timeA', 'timeB')},
        ),
    ]
