# Generated by Django 3.0.4 on 2023-06-22 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0005_auto_20230622_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jogo',
            options={'ordering': ['fase', 'chave'], 'verbose_name': 'jogo', 'verbose_name_plural': 'jogos'},
        ),
    ]
