# Generated by Django 3.0.4 on 2023-05-28 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscricao', '0002_auto_20230528_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dupla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao_dupla', models.IntegerField(blank=True, null=True, verbose_name='Pontuação somada atletas')),
                ('is_active', models.BooleanField(default=True, help_text='Se ativo, o curso pode ser usado no sistema', verbose_name='Ativo')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
                ('atleta_direita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atleta_direita', to='inscricao.Inscricao', verbose_name='Direita *')),
                ('atleta_esquerda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atleta_esquerda', to='inscricao.Inscricao', verbose_name='Esquerda *')),
            ],
            options={
                'verbose_name': 'dupla',
                'verbose_name_plural': 'duplass',
                'ordering': ['atleta_direita__etapa', '-pontuacao_dupla'],
            },
        ),
    ]
