# Generated by Django 3.0.4 on 2023-05-29 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dupla', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dupla',
            options={'ordering': ['atleta_direita__etapa', '-pontuacao_dupla'], 'verbose_name': 'dupla', 'verbose_name_plural': 'duplas'},
        ),
        migrations.RemoveField(
            model_name='dupla',
            name='is_active',
        ),
    ]
