# Generated by Django 3.0.4 on 2023-05-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Use dd/mm/aaaa', verbose_name='Data da etapa *')),
                ('local', models.CharField(choices=[('STAR PADEL', 'Star Padel')], default='STAR PADEL', help_text='* Campos obrigatórios', max_length=15, verbose_name='Local da etapa *')),
                ('total_duplas', models.IntegerField(blank=True, default=0, null=True, verbose_name='Total de duplas')),
                ('total_chaves', models.IntegerField(blank=True, default=0, null=True, verbose_name='Total de chaves')),
                ('is_active', models.BooleanField(default=True, help_text='Se ativo, o curso pode ser usado no sistema', verbose_name='Ativo')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
            ],
            options={
                'verbose_name': 'etapa',
                'verbose_name_plural': 'etapas',
                'ordering': ['-data'],
            },
        ),
    ]
