# Generated by Django 3.0.4 on 2023-05-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='inscritos_direita',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total de direitas inscritos'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='inscritos_esquerda',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total de esquerdas inscritos'),
        ),
    ]
