# Generated by Django 3.0.4 on 2023-05-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapa', '0002_auto_20230522_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='grupo',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=5, null=True, verbose_name='Turma Longeva'),
        ),
    ]
