# Generated by Django 3.0.4 on 2023-06-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapa', '0004_auto_20230528_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='inscricoes_abertas',
            field=models.BooleanField(default=True, help_text='Quando desejar, pode encerrar as inscrições', verbose_name='A Etapa está com inscrições abertas?'),
        ),
    ]
