# Generated by Django 3.0.4 on 2023-05-30 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etapa', '0004_auto_20230528_1819'),
        ('dupla', '0002_auto_20230528_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1, verbose_name='Nome')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='etapa.Etapa')),
            ],
            options={
                'ordering': ['nome'],
                'unique_together': {('nome', 'etapa')},
            },
        ),
        migrations.CreateModel(
            name='ChaveDupla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chave.Chave')),
                ('dupla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dupla.Dupla')),
            ],
        ),
    ]
