# Generated by Django 3.0.4 on 2023-05-31 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chave', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chavedupla',
            options={'ordering': ['chave']},
        ),
    ]
