# Generated by Django 3.0.4 on 2023-06-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chave', '0002_auto_20230531_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chave',
            name='nome',
            field=models.CharField(help_text='A ou B ou C ou D ou ...', max_length=1, verbose_name='Nome'),
        ),
    ]
