# Generated by Django 3.0.4 on 2023-06-13 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dupla', '0002_auto_20230528_2104'),
        ('chave', '0003_auto_20230611_1611'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chavedupla',
            unique_together={('dupla',)},
        ),
    ]
