# Generated by Django 3.0.4 on 2023-05-22 22:09

import django.contrib.auth.models
from django.db import migrations, models
import usuario.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('tipo', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('TREINADOR', 'Treinador'), ('ATLETA', 'Atleta')], default='ATLETA', help_text='* Campos obrigatórios', max_length=15, verbose_name='Tipo do usuário *')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome completo *')),
                ('apelido', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apelido')),
                ('data_nascimento', models.DateField(blank=True, help_text='Use dd/mm/aaaa', null=True, verbose_name='Data nascimento *')),
                ('email', models.EmailField(blank=True, help_text='O email é fundamental para recuperar senha', max_length=100, null=True, verbose_name='Email ')),
                ('celular', models.CharField(db_index=True, help_text='Use DDD, por exemplo 55987619832', max_length=11, unique=True, verbose_name='Número celular com DDD')),
                ('posicao', models.CharField(choices=[('DIREITA', 'Direita'), ('ESQUERDA', 'Esquerda'), ('AMBAS', 'Ambas')], max_length=8, verbose_name='Posição na quadra *')),
                ('pontuacao', models.IntegerField(blank=True, default=0, null=True, verbose_name='Pontuação do atleta')),
                ('qtd_etapas_jogadas', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantidade de etapas que participou')),
                ('is_active', models.BooleanField(default=False, help_text='Se ativo, o usuário tem permissão para acessar o sistema', verbose_name='Ativo')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
            ],
            options={
                'verbose_name': 'longevo',
                'verbose_name_plural': 'longevos',
                'ordering': ['nome'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
                ('administradores', usuario.models.AdministradorAtivoManager()),
                ('treinadores', usuario.models.TreinadorAtivoManager()),
            ],
        ),
    ]
