# Generated by Django 3.0.4 on 2023-05-21 22:45

import django.contrib.auth.models
from django.db import migrations, models
import usuario.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('tipo', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('TÉCNICO', 'Técnico'), ('ATLETA', 'Atleta')], default='ATLETA', help_text='* Campos obrigatórios', max_length=15, verbose_name='Tipo do usuário *')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome completo *')),
                ('apelido', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apelido')),
                ('email', models.EmailField(max_length=100, verbose_name='Email *')),
                ('celular', models.CharField(db_index=True, help_text='Use DDD, por exemplo 55987619832', max_length=11, unique=True, verbose_name='Número celular com DDD *')),
                ('posicao', models.CharField(choices=[('DIREITA', 'Direita'), ('ESQUERDA', 'Esquerda'), ('AMBAS', 'Ambas')], max_length=8, verbose_name='Posição na quadra *')),
                ('pontuacao', models.IntegerField(blank=True, null=True, verbose_name='Pontuação do atleta')),
                ('qtd_etapas_jogadas', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de etapas que participou')),
                ('is_active', models.BooleanField(default=False, help_text='Se ativo, o usuário tem permissão para acessar o sistema', verbose_name='Ativo')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
            ],
            options={
                'verbose_name': 'longevo',
                'verbose_name_plural': 'longevos',
                'ordering': ['nome'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
                ('administradores', usuario.models.AdministradorAtivoManager()),
                ('enfermeiros', usuario.models.EnfermeiroAtivoManager()),
                ('tecnicos', usuario.models.TecnicoAtivoManager()),
                ('medicos', usuario.models.MedicoAtivoManager()),
                ('tecnicos_enfermeiros', usuario.models.TecnicoEnfermeiroAtivoManager()),
            ],
        ),
    ]
