# Generated by Django 3.0.4 on 2023-05-21 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apelido',
        ),
    ]
