# Generated by Django 3.0.4 on 2023-05-22 23:07

import django.contrib.auth.models
from django.db import migrations
import usuario.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
                ('administradores', usuario.models.AdministradorAtivoManager()),
                ('treinadores', usuario.models.TreinadorAtivoManager()),
                ('atletas', usuario.models.AtletaAtivoManager()),
            ],
        ),
    ]
