# Generated by Django 3.0.4 on 2023-05-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_remove_usuario_apelido'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apelido',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apelido'),
        ),
    ]
