# Generated by Django 3.0.4 on 2023-05-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20230522_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['tipo', 'nome'], 'verbose_name': 'longevo', 'verbose_name_plural': 'longevos'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='grupo',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=2, null=True, verbose_name='Turma Longeva'),
        ),
    ]
