# Generated by Django 3.0.4 on 2023-05-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuario_apelido'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(null=True, verbose_name='Data nascimento *'),
        ),
    ]
