# Generated by Django 3.0.4 on 2023-05-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20230525_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['tipo', 'grupo', '-pontuacao', '-qtd_etapas_jogadas', 'nome'], 'verbose_name': 'longevo', 'verbose_name_plural': 'longevos'},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='grupo',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AMBAS', 'Ambas')], max_length=5, null=True, verbose_name='Turma Longeva'),
        ),
    ]
