# Generated by Django 3.0.4 on 2023-05-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_usuario_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(help_text='Use dd/mm/aaaa', null=True, verbose_name='Data nascimento *'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pontuacao',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Pontuação do atleta'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='qtd_etapas_jogadas',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantidade de etapas que participou'),
        ),
    ]
