# Generated by Django 3.0.4 on 2023-05-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20230522_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(blank=True, help_text='Use dd/mm/aaaa', null=True, verbose_name='Data nascimento *'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, help_text='O email é fundamental para recuperar senha', max_length=100, null=True, verbose_name='Email '),
        ),
    ]
